climate:
  - platform: xiaomi_miio_airconditioningcompanion
    name: Aqara Air Conditioning Companion
    host: 192.168.10.103
    token: b1c64ea70b2accd4b25b156a53d96270
    target_sensor: sensor.temperature_158d0001f53706
    scan_interval: 60