switch:
  - platform: mqtt
    name: Door Switch
    command_topic: "ESP0501/gpio/0"
    state_topic: "ESP0501/doorlock/state"
    payload_on: 1
    payload_off: 0
    state_on: 1
    state_off: 0
  - platform: mqtt
    name: USB Switch
    command_topic: "ESP0502/gpio/0"
    state_topic: "ESP0502/usb/state"
    payload_on: 1
    payload_off: 0
    state_on: 1
    state_off: 0